---
- hosts: all
  tasks:
  - name: change PasswordAuth
    lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    line: PasswordAuthentication yes

  - name: restart sshd
    become: true
    become_user: root
    shell:
      cmd: systemctl restart sshd
