---
- hosts: mysql
  tasks:
  - name: Update apt-get repo and cache
    apt:
      update_cache=yes
  - name: Install pip3
    apt:
      name: python3-pip
      state: present
  - name: Install pymysql
    pip:
      name: pymysql
      state: present
  - name: Install mysql-server
    apt:
      name: mysql-server
      state: present
  - name: Start SQL Service
    service:
      name: mysql
      state: restarted
  - name: create new database
    mysql_db:
      login_host: # ip host
      login_user: # user
      login_password: # pass
      name: dumbplay
      state: present
  - name: create user
    mysql_user:
      name: # add user
      password: # pass
      login_host: # ip host
      login_user: # user
      login_password: # pass
      host: '%'

