global:
 scrape_interval: 10s
scrape_configs:
 - job_name: 'prometheus_metrics'
   scrape_interval: 5s
   static_configs:
     - targets: ['3.236.105.174:9090']
 - job_name: 'node_exporter_metrics'
   scrape_interval: 5s
   static_configs:
     - targets: ['3.227.83.229:9100','100.25.215.99:9100','52.90.13.6:9100','3.235.74.139:9100']